### Cadastrar folha
POST https://localhost:5001/api/folha/cadastrar
Content-Type: application/json

{
    "Id": 1,
    "Mes" : 1,
    "Ano": 2021
    "Horas": 40,
    "ValorHora": 25
    "FuncionarioId": 1
}

### Listar folhas
GET https://localhost:5001/api/folha/listar
Content-Type: application/json

### Deletar folha pelo id
DELETE https://localhost:5001/api/folha/deletar/1

